-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.cancel_enrollments
(

    CONSTRAINT cancel_enrollments_pkey PRIMARY KEY (id_cancel_enrollments),
    CONSTRAINT uk_g2l8orlf7q5kcf549ldtkcxq8 UNIQUE (enrollments_id_enrollment)
);

CREATE TABLE IF NOT EXISTS public.classroom
(

    CONSTRAINT classroom_pkey PRIMARY KEY (id_classroom),
    CONSTRAINT uk_e8in7qqerivmlm33kpbaw5cy8 UNIQUE (id_course),
    CONSTRAINT uk_kvr4p1q813nyirn5sh2r6an61 UNIQUE (id_teacher)
);

CREATE TABLE IF NOT EXISTS public.courses
(

    CONSTRAINT courses_pkey PRIMARY KEY (id_course)
);

CREATE TABLE IF NOT EXISTS public.documents_type
(

    CONSTRAINT documents_type_pkey PRIMARY KEY (id_documents_type)
);

CREATE TABLE IF NOT EXISTS public.enrollments
(

    CONSTRAINT enrollments_pkey PRIMARY KEY (id_enrollment)
);

CREATE TABLE IF NOT EXISTS public.exam
(

    CONSTRAINT exam_pkey PRIMARY KEY (id_exam),
    CONSTRAINT uk_uckxoqdy70owe62bbt55snci UNIQUE (id_course)
);

CREATE TABLE IF NOT EXISTS public.score
(

    CONSTRAINT score_pkey PRIMARY KEY (id_score),
    CONSTRAINT uk_bjtnmhvsy8np65k67b66byjrq UNIQUE (exam_id_exam)
);

CREATE TABLE IF NOT EXISTS public.students
(

    CONSTRAINT students_pkey PRIMARY KEY (id_student)
);

CREATE TABLE IF NOT EXISTS public.teacher_course
(

    CONSTRAINT teacher_course_pkey PRIMARY KEY (id_teacher, id_course)
);

CREATE TABLE IF NOT EXISTS public.teachers
(

    CONSTRAINT teachers_pkey PRIMARY KEY (id_teacher)
);

CREATE TABLE IF NOT EXISTS public.users
(

    CONSTRAINT users_pkey PRIMARY KEY (usuario_id)
);

CREATE TABLE IF NOT EXISTS public.users_entity
(

    CONSTRAINT users_entity_pkey PRIMARY KEY (usuario_id)
);

ALTER TABLE IF EXISTS public.cancel_enrollments
    ADD CONSTRAINT fkbsofi7hdcf9ye6u7wc6wo9vig FOREIGN KEY (enrollments_id_enrollment)
    REFERENCES public.enrollments (id_enrollment) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS uk_g2l8orlf7q5kcf549ldtkcxq8
    ON public.cancel_enrollments(enrollments_id_enrollment);


ALTER TABLE IF EXISTS public.classroom
    ADD CONSTRAINT fk6c17dv8o2ti1bbxj5g0r1g4a8 FOREIGN KEY (id_course)
    REFERENCES public.courses (id_course) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS uk_e8in7qqerivmlm33kpbaw5cy8
    ON public.classroom(id_course);


ALTER TABLE IF EXISTS public.classroom
    ADD CONSTRAINT fkheekgpblfn12ejyoxcci62x5v FOREIGN KEY (id_teacher)
    REFERENCES public.teachers (id_teacher) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS uk_kvr4p1q813nyirn5sh2r6an61
    ON public.classroom(id_teacher);


ALTER TABLE IF EXISTS public.enrollments
    ADD CONSTRAINT fk53v8lki0strvb8f81chut5xwk FOREIGN KEY (course_id_course)
    REFERENCES public.courses (id_course) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.enrollments
    ADD CONSTRAINT fkbawq4xu0tdvul6fvxc6sb33dp FOREIGN KEY (student_id_student)
    REFERENCES public.students (id_student) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.exam
    ADD CONSTRAINT fki9cxwk7e5huvl3xevlfyph8yu FOREIGN KEY (id_course)
    REFERENCES public.courses (id_course) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS uk_uckxoqdy70owe62bbt55snci
    ON public.exam(id_course);


ALTER TABLE IF EXISTS public.score
    ADD CONSTRAINT fk7hek04u5dckc6uglwa2d21yed FOREIGN KEY (teacher_id_teacher)
    REFERENCES public.teachers (id_teacher) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.score
    ADD CONSTRAINT fkgnarvic9dgohfxr01e1f4x69w FOREIGN KEY (exam_id_exam)
    REFERENCES public.exam (id_exam) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS uk_bjtnmhvsy8np65k67b66byjrq
    ON public.score(exam_id_exam);


ALTER TABLE IF EXISTS public.score
    ADD CONSTRAINT fkvfbmyc79exv3e1llcjf8w2o1 FOREIGN KEY (student_id_student)
    REFERENCES public.students (id_student) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.students
    ADD CONSTRAINT fk3e86wqntuh7ox4hwgs0qux1ix FOREIGN KEY (document_type_id_document_type)
    REFERENCES public.documents_type (id_documents_type) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.students
    ADD CONSTRAINT fkpih0oqg13p0fqbk0ledjua3av FOREIGN KEY (id_classroom)
    REFERENCES public.classroom (id_classroom) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.teacher_course
    ADD CONSTRAINT fkc9marin8ftaxpancdwom11jj9 FOREIGN KEY (id_course)
    REFERENCES public.courses (id_course) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.teacher_course
    ADD CONSTRAINT fkq762snusp4oiax6ys5xsf6dvy FOREIGN KEY (id_teacher)
    REFERENCES public.teachers (id_teacher) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.teachers
    ADD CONSTRAINT fk6b5yuhgx1p46vfjcq2knogyer FOREIGN KEY (document_type_id_document_type)
    REFERENCES public.documents_type (id_documents_type) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;